### ISSUE TITLE
Storage build failed

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#268]
Generated and ran build:

```
generated\api\Models\Api20190401\StorageAccountCreateParameters.cs(5,59): error CS0535: 'StorageAccountCreateParameters' does not implement interface member 'IStorageAccountCreateParameters.IdentityType.set' [C:\Users\niassis\source\repos\generating\azu
re-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20171001\StorageAccount.cs(5,43): error CS0535: 'StorageAccount' does not implement interface member 'IStorageAccount.IdentityType.set' [C:\Users\niassis\source\repos\generating\azure-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20190401\StorageAccount.cs(5,43): error CS0535: 'StorageAccount' does not implement interface member 'IStorageAccount.IdentityType.set' [C:\Users\niassis\source\repos\generating\azure-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20180201\StorageAccount.cs(5,43): error CS0535: 'StorageAccount' does not implement interface member 'IStorageAccount.IdentityType.set' [C:\Users\niassis\source\repos\generating\azure-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20180701\StorageAccount.cs(5,43): error CS0535: 'StorageAccount' does not implement interface member 'IStorageAccount.IdentityType.set' [C:\Users\niassis\source\repos\generating\azure-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20171001\StorageAccountCreateParameters.cs(5,59): error CS0535: 'StorageAccountCreateParameters' does not implement interface member 'IStorageAccountCreateParameters.IdentityType.set' [C:\Users\niassis\source\repos\generating\azu
re-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20190401\StorageAccountUpdateParameters.cs(7,59): error CS0535: 'StorageAccountUpdateParameters' does not implement interface member 'IStorageAccountUpdateParameters.IdentityType.set' [C:\Users\niassis\source\repos\generating\azu
re-powershell\src\Storage\Az.Storage.csproj]
generated\api\Models\Api20171001\StorageAccountUpdateParameters.cs(7,59): error CS0535: 'StorageAccountUpdateParameters' does not implement interface member 'IStorageAccountUpdateParameters.IdentityType.set' [C:\Users\niassis\source\repos\generating\azu
re-powershell\src\Storage\Az.Storage.csproj]
C:\Users\niassis\source\repos\generating\azure-powershell\src\Storage\build-module.ps1 : Compilation failed.
At C:\Users\niassis\source\repos\generating\azure-powershell\src\Storage\build-module.ps1:70 char:3
+   Write-Error 'Compilation failed.'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-module.ps1
```

**Comment by fearthecowboy** [comment]
Works with 2.0.431

**Comment by niander** [comment]
Not working with the newest readme files in generation branch
